name: CICD Test
run-name: Running
on:
  push:
    branches:
      - production
      - 'releases/**'

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: buddytests3
  AWS_CODE_DEPLOY_APPLICATION: cicd-test-CD
  AWS_CODE_DEPLOY_GROUP: cicid-test-CD-group
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  SSL_KEYSTORE_PASSWORD: ${{ secrets.SSL_KEYSTORE_PASSWORD }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
      - name: production 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: production

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew clean build -x test

      - name: AWS credential 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}

      - name: S3에 업로드
        run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://buddytests3/cicdtest/$GITHUB_SHA.zip --source .

      - name: Deploy to server
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SSL_KEYSTORE_PASSWORD: ${{ secrets.SSL_KEYSTORE_PASSWORD }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          scp -r ./build/libs/buddy-0.0.1-SNAPSHOT.jar ubuntu@52.78.175.86:/home/ubuntu/
          ssh ubuntu@52.78.175.86 "
            export DB_USERNAME=${{ secrets.DB_USERNAME }};
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }};
            export SSL_KEYSTORE_PASSWORD=${{ secrets.SSL_KEYSTORE_PASSWORD }};
            export KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }};
            export KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }};
            export JWT_SECRET=${{ secrets.JWT_SECRET }};
            nohup java -jar /home/ubuntu/buddy-0.0.1-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &
          "
